use afterlight_spike::common::{
    CANCEL_TAG, CLAIM_TAG, FUND_TAG, HEARTBEAT_TAG, REQUEST_TAG, VETO_TAG, message_hash,
};
use starknet::ContractAddress;

// These fixed outputs were generated by client/src/messages.ts::authorizationHash.
// Recomputing the same inputs through Cairo's message_hash makes the fixture a
// real cross-language compatibility check rather than two TypeScript code paths.
const CHAIN_ID: felt252 = 0x534e5f4d41494e;
const VAULT_ID: felt252 = 0xabc;
const AMOUNT: u128 = 10_000_000_000_000_000_000;
const EXPECTED_STATE: u8 = 1;
const EPOCH: u64 = 2;
const NONCE: u64 = 3;
const SIGNER_KEY: felt252 = 0x444;
const NOTE_ID: felt252 = 0x555;
const VALID_UNTIL: u64 = 1_787_540_000;

fn vector_hash(tag: felt252, extras: Span<felt252>) -> felt252 {
    let contract_address: ContractAddress = 0x1234.try_into().unwrap();
    let token: ContractAddress = 0x999.try_into().unwrap();
    message_hash(
        tag,
        CHAIN_ID,
        contract_address,
        VAULT_ID,
        token,
        AMOUNT,
        EXPECTED_STATE,
        EPOCH,
        NONCE,
        SIGNER_KEY,
        NOTE_ID,
        VALID_UNTIL,
        extras,
    )
}

#[test]
fn fund_hash_matches_typescript_vector() {
    let actual = vector_hash(FUND_TAG, array![1, 0x666, 120, 60].span());
    assert(
        actual == 0x235558e175c62beb0f26c05a9b292a40a8c4a5146544cc637d97ca700f70f22,
        'TS FUND hash mismatch',
    );
}

#[test]
fn cancel_refund_hash_matches_typescript_vector() {
    let actual = vector_hash(CANCEL_TAG, array![].span());
    assert(
        actual == 0x67d0e21e3670e00343b7d9d5fd9bf56759d06c22a1c21dff9b99428f3ea3ea4,
        'TS CANCEL hash mismatch',
    );
}

#[test]
fn claim_hash_matches_typescript_vector() {
    let actual = vector_hash(CLAIM_TAG, array![1_787_539_000, 1_787_539_900].span());
    assert(
        actual == 0x4349ce2da049d1ed496f65c1ba3742ca997c2f102db2b459dd56cd76dca3140,
        'TS CLAIM hash mismatch',
    );
}

#[test]
fn heartbeat_hash_matches_typescript_vector() {
    let actual = vector_hash(HEARTBEAT_TAG, array![1_787_538_000].span());
    assert(
        actual == 0x7e730e8e4f0855df7c159438eeb2606d99c22385bb9eb81188ef4ef85a0c79f,
        'TS HEARTBEAT hash mismatch',
    );
}

#[test]
fn request_hash_matches_typescript_vector() {
    let actual = vector_hash(REQUEST_TAG, array![1_787_538_000].span());
    assert(
        actual == 0x129fabc595665af491b544f9079e3e15594de0f25f8858021d3376183c7d95d,
        'TS REQUEST hash mismatch',
    );
}

#[test]
fn veto_hash_matches_typescript_vector() {
    let actual = vector_hash(VETO_TAG, array![1_787_539_000, 1_787_539_900].span());
    assert(
        actual == 0x4623d9e97a90ca2cda54aca217896ae98dcae852e8b9c600187d0b27a7de222,
        'TS VETO hash mismatch',
    );
}
